import {MigrationInterface, QueryRunner,getConnection} from "typeorm";

export class InsertRisks1637247565120 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {

        
        await getConnection()
        .createQueryBuilder()
        .insert()
        .into('clarisa_risks')
        .values([
            {
                id: 1,
                generic_risks: "Failure to articulate a value proposition for the Initiative that outlines clearly the pathway from research to impact",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 2,
                generic_risks: "Failure to specify research questions and mismatch with CGIAR’s core strengths and capabilities",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 3,
                generic_risks: "Influencing and advancing policy and regulatory environment implications not adequately understood or accounted for by the Initiative, hindering the uptake of innovations",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 4,
                generic_risks: "Inappropriate geographic targeting",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 5,
                generic_risks: "Poor strategic positioning of the Initiative or alignment with other Initiatives (including due to lack of portfolio cohesion)",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 6,
                generic_risks: "Topics that could benefit multiple Initiatives are not embedded throughout the entire portfolio (i.e. digital technologies, foresights and trade-offs dialogue) impacting Initiative's efficiency and decision making",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 7,
                generic_risks: "Unable to plan for unexpected changes, emerging opportunities, and synergies with other Initiatives",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 8,
                generic_risks: "Conflicting intended or unintended consequences of technologies/innovations for natural resources, GHG emissions, and social and economic aspects impacting objectives and reputation",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 9,
                generic_risks: "Initiative's dependency on legacy work such as valued elements developed through the CRPs (infrastructure, relationships, processes, tools, data and innovations) that are not carried forward",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 10,
                generic_risks: "Unclear accountability while in transition",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 11,
                generic_risks: "Lack of learning from prior CGIAR evaluations and other assessments",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 12,
                generic_risks: "Failure to identify and operationalise mission critical partnerships (incl. scaling and research) or partnerships lost (i.e. non-One CGIAR partners)",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 13,
                generic_risks: "Lack of sense of ownership of the Research and Innovation Strategy by public, private, and civil society stakeholders involved in foresight and priority-setting processes",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 14,
                generic_risks: "Inappropriate balance between private and public goods generated by the portfolio may affect Initiative objectives",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 15,
                generic_risks: "Unable to incentivize right behaviours by farmers, value chain actors, and policy makers needed for adoption",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 16,
                generic_risks: "Capability, and capacity constraints within and across the regions may hinder the uptake of innovations",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 17,
                generic_risks: "Lack of meaningful partner engagement in Initiative design and delivery",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 18,
                generic_risks: "Lack of viable career paths for junior and mid-level scientists",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 19,
                generic_risks: "Failure to attract, engage, develop and retain talent",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 20,
                generic_risks: "Unable to tap into new ideas and approaches and have the right balance of innovations to attract new funders",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 21,
                generic_risks: "Lack of a systematic and integrated approach for monitoring and evaluation at the outcome level impacts Initiative's objectives",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 22,
                generic_risks: "Lack of capacity and/or effective systems to effectively operationalise theory of change",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 23,
                generic_risks: "Reorganization (One CGIAR or other i.e. institutional or programmatic changes) impacts Initiative's execution",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 24,
                generic_risks: "Business interruption or delays due to pandemic, war, natural disaster or other incident affecting the Initiative or key dependencies",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 25,
                generic_risks: "Data management and systems not fit for purpose or outdated affecting Initiative's efficiency",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 26,
                generic_risks: "Funding uncertainty, budget insecurity or delay due to geopolitical events /disasters shifting funders' priorities",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 27,
                generic_risks: "Initiative relies on assumption that increase in funding would result from One CGIAR transition",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 28,
                generic_risks: "Initiative relies on assumption of stable funding for 3 years",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 29,
                generic_risks: "Initiative relies on assumption that pooled funding will be the main source compared to bilateral",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 30,
                generic_risks: "Inability to move genetic material between countries that do not have developed systems to accept it",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 31,
                generic_risks: "Genetically enhanced plant materials not widely accepted",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 32,
                generic_risks: "Unable to achieve a smooth transition of host-country agreements changes",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            },
            {
                id: 33,
                generic_risks: "Ethical/behavioural (i.e. failure to protect children and vulnerable adults), financial irregularity, data privacy incident leading to reputational event affecting Initiative",
                created_at: "2021-11-18 15:59:15",
                updated_at: "2021-11-18 15:59:15"
            }
         ])
        .execute();


    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
