import {getRepository, MigrationInterface, QueryRunner} from 'typeorm';
import {InitiativeTeam} from '../entity/InitiativesTeam';

export class InsertHumanResourcesTeamInitiatives1640121657676
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const initiativeTeamRepo = getRepository(InitiativeTeam);

    const teamPerIntv = await initiativeTeamRepo.find();
    teamPerIntv.map((t) => (t.active = false));

    const updatedTeam = await initiativeTeamRepo.save(teamPerIntv);

    const insertSQL = `
        INSERT INTO initiative_team (category, area_expertise, key_accountabilities, human_resources_id, active)
VALUES ("Research","Non-Research","Project management and MEL",3,1),
("Research","Non-Research","Scaling readiness assessment and process, communication",3,1),
("Research","Research","Crop-specific research and partnership management, scientific leadership, breeding processes",3,1),
("Research support","Research","Portfolio management at the intersection of breeding, socio-economics and stakeholder perspectives.",3,1),
("Research support","Research","Molecular and field-based plant breeding, quantitative genetics, data-driven decision making",3,1),
("Research","Research","Genetics (quantitative, molecular, physiological).",3,1),
("Research","Research","Physiology, pathology, nutritional and end-use quality assessments, trialing team",3,1),
("Research support","Research/Non-Research","Network coordination, public-private partnerships",3,1),
("Research","Research","On-farm variety evaluation at scale",3,1),
("Research support","Research / Non-Research","Execute operations for breeding, phenotyping and TD&D teams,",3,1),
("Research support","Non-research","Finance, administration, legal, HR",3,1),
("Research support","Non-research","Communications",3,1),
("Research support","Research / non-research","Distinct technical and management expertise",3,1),
("Research","Research","Research and partnership management, scientific leadership, Strategic Vision, Team Building",3,1),
("Research","Research","Research and partnership management, scientific leadership, stakeholder management",3,1),
("Research support","Strategic management","Initiative Leadership, lead Annual Workplan Budget (AWBP), delivery, monitoring and reporting, links across other Initiatives and CGIAR, external Initiative representation.",21,1),
("Research support","WP strategic management","Lead WP AWPB and implementation within and across WPs; manage research and research support staff.",21,1),
("Research support","MELIA","Support Initiative Leadership to coordinate Results Framework and manage delivery of Outputs and contributions to Outcomes.",21,1),
("Research support","Gender / social inclusion","Coordination and leadership of Reach-Benefit-Empower-Transform (RBET) strategy for F2R-CWANA.",21,1),
("Research support","Fragility","Lead on impact of conflict exposure/fragility; lead/monitor situation in-country and advise adjustments responsive to new sources of risk.",21,1),
("Research support","Communications / outreach","Lead transformation from research to information, communications tools and policy practice and outreach under guidance of Initiative leadership (Research support).",21,1),
("Research support","Administrative","Administrative, financial and HR leadership under the guidance of Initiative Management (Research Support).",21,1),
("Research","Socio-economics","Lead development of tools for adoption and impact assessments of innovations and monitor socio-economic surveys.",21,1),
("Research","Policy","Lead on partner cooperation and strengthening institutional capacity, support and engagement with policies and instruments.",21,1),
("Research","Agricultural innovation and technology","Lead and coordinate technical assistance for innovations and impact and develop sustainable road maps for wide scale adoption in-field; assess capacity building opportunities; and development of joint knowledge sharing activities.",21,1),
("Research","Data management and analysis specialist","Support survey design, sampling, collection, analysis and visualization; Support development of data collection instruments, recoding, reporting and disseminating findings and recommendations and lessons learned.",21,1),
("Research","Agrobiodiversity","Lead on status/threats assessment; development and demonstration of management plan, training; technical backstopping and training.",21,1),
("Research","FAP","Introduction and demonstration of “Farming with alternative pollinators”.",21,1),
("Research","Plant breeders","Design experiments to support release/registration of adapted and farmer/industry/consumer preferred varieties for crops and facilitate dissemination/adoption.",21,1),
("Research","Seed systems and product management","Lead seed system research; studies on early generation seed production models; provide data to support updated policies and regulatory frameworks for functioning of seed systems at national and regional levels; and strengthen the capacity of seed value chain actors.",21,1),
("Research","Socio-economics and policy","Lead research and analysis of seed production / marketing models; adoption/impact of genetic innovations; and policy for biodiversity and seed systems.",21,1),
("Research","Data management","Ensure data collected in various research activities are collected, managed and analysed.",21,1),
("Research","Systems agronomy / Cropping systems","Cropping systems optimization, conservation agriculture (CA) based sustainable intensification, G x E x M x S interaction and recommendation domains of agronomic management targeted crop varieties, business models and science evidence-based policies, capacity development on CA.",21,1),
("Research","Water management / hydrology","On-farm water management - designing/targeting precision water management tools/techniques; improving crop water productivity; state of the natural resource base.",21,1),
("Research","Soil scientist","Develop soil health frameworks for crop-livestock systems across participatory research and innovation platforms.",21,1),
("Research","Cropping system simulation","Coordinate scenario analysis for designing cropping systems, management practices for diverse biophysical and socio-economic environment.",21,1),
("Research","Mechanization specialist","Designing/ scaling appropriate mechanization solutions appropriate for dryland systems and innovation platforms.",21,1),
("Research","Geospatial and data","Geospatial analysis and mapping state of natural resources, yield gap analysis.",21,1),
("Research","Farming systems modelling","Farming systems analysis, designing climate resilient farming systems and landscapes options with synergies and trade-offs, and targeting.",21,1),
("Research","Socio-economics and policy","Lead management practices to solutions; recommendation for management practices and varieties/genotypes suitable to specific farming systems.",21,1),
("Research","IWRM","Plan, design, and manage the coordinated development and management of water, land and related resources.",21,1),
("Research","Hydrology and agricultural water management","Integrated assessments; quantitative and qualitative field experiments (incl. design, data collection, analysis).",21,1),
("Research","Water governance","Co-Design the water governance guidelines including tailoring to local conditions and conduct water governance analysis to support scaling.",21,1),
("Research","TWW","Lead the TWW socio-economic feasibility study and facilitate the group discussion and inform policy development.",21,1),
("Research","Water accounting","Support integrated assessments and policy activities including policy development/coherence; design / conduct water accounting.",21,1),
("Research","Policy analysts","Support scaling; knowledge synthesis; cooperation to support policy / decision-making process; outreach / science-policy activities’ development, and assessments.",21,1),
("Research","Remote sensing data / GIS","Support the data acquisition and lead the co-design the dashboard’s development.",21,1),
("Research","DSS and model integration","Lead the integrated assessment including coding and integrated modelling analysis and assessment.",21,1),
("Research","Climate science, crop and climate hazard modelling","Lead climate risk analyses of selected value chains in CWANA; climate analytics and early warning systems to characterize innovation platforms.",21,1),
("Research","Economics","Identify, evaluate, prioritize digital solutions for climate risks management in value chains; assess business case; lead financial/impact evaluation of digital solutions.",21,1),
("Research","Data science/augmentation","Support development and integration of digital solutions for climate risk management. Facilitates digitalization of agriculture, tools and data management.",21,1),
("Research","Incubation/acceleration","Lead incubator/accelerator programs on digital solutions; develop pipelines of bankable digital solutions to be brought to market and scaled (Research support).",21,1),
("Research","Sustainable finance","Lead strategy and digital investment roadmaps with public/private investors to connect with national/regional/global public and private investors (Research support).",21,1),
("Research","Chief Executive Officer (CEO), Chief Data Officer (CDO), Chief Scientific Officer (CSO), Chief Growth Officer (CGO)","Coordinate WPs (DELIVER – CGO, TRANFORM – CDO, INNOVATE – CSO, ORGANIZE – CEO)",8,1),
("Research support","Regional coordination","Facilitate Use Cases, track demand, communication",8,1),
("Research support","Program coordination - technical & capacity","Technical coordination of development; capacity development coordination",8,1),
("Research support","Administrative support","Assist management team and regional coordinators",8,1),
("Research","Field agronomy","Implement Use Case workflows in specific geographies",8,1),
("Research","Agronomy programme management","Provide regional support and coordination for Use Cases",8,1),
("Research","Social scientist - scaling","Support and embed scaling readiness in Use Cases",8,1),
("Research","Social science - behavioral change","Design mechanisms for farmer adoption of advisories",8,1),
("Research","Data science, climate, soil, field analytics, crop modelling","Support Use Cases by developing data and analytics solutions and refining validation protocols",8,1),
("Research","Data management and standards","Assist with data management towards open & FAIR outcomes",8,1),
("Research","Diverse expert consultancies","Support development of analytics responding to gender, climate, soil health needs",8,1),
("Research support","System administration","VMware, Cloud solution & server set-up, maintenance",8,1),
("Research support","Software development","Development of infrastructure and tooling",8,1),
("Research","Data science","Integrate strategic R&D products in the TRANSFORM pipeline",8,1),
("Research","Weed management, mechanization, farming systems, gender, biofortification, soil health, climate adaptation, policy","Lead strategic research projects, supervise PhD and MSc research projects, decide on new investments in new strategic R&D projects and lead CoPs around thematic areas",8,1),
("Research","ME&L","Operationalize MELIA system",8,1),
("Research","Socioeconomics - foresight, ex-ante analysis, segmentation","Lead priority setting exercises, including ex-ante analytics and projected benefits",8,1),
("Research","Data science","Develop tools for yield gap decomposition for Use Cases",8,1),
("Research","Socioeconomics - impact assessment","Implement RCTs, baseline and panel studies, and impact assessment",8,1),
("Research","Agronomy-soil science","Assessment of the agronomic gain KPI framework",8,1),
("Research support","Program management","Facilitate planning and technical/financial reporting",8,1),
("Research support","Communications","Facilitate strategic communication",8,1),
("Research support","ICT Specialist","Operate One-Stop-Shop for agronomy solutions",8,1),
("Research","Agricultural. advisory specialist /agronomist","Develop and monitor spatial organization on farm and landscape",23,1),
("Research","Anthropologist/ethnobotanist","Document ethnobotanic information",23,1),
("Research","Biodiversity expert","Describe and characterize biodiversity",23,1),
("Research","Capacity expert","Develop training and extension packages",23,1),
("Research","Participatory Research Expert","Develop participatory research protocols",23,1),
("Research","Civil Engineer","Supervise the establishment of the National Uptake Centers",23,1),
("Research","Crop scientist","Develop PPB schemes and manage on farm experiments",23,1),
("Research","Ecologist and landscape scientist/environmental scientist","Develop framework and monitor ecosystem services",23,1),
("Research","Education specialist","Develop and implement education programs",23,1),
("Research","Economist","Cost-benefit analysis, market demand, cost-benefits, return on investments, NPS impact assessment",23,1),
("Research","Farm and ecological modeler","Develop and implement crop rotation and intercropping schemes",23,1),
("Research","Financial advisor","Support early adopters with implementation of waste-based business models to ensure sustainability",23,1),
("Research","Gender and diversity specialist","Ensure Gender and inclusion are key in project implementation and co-design of solutions",23,1),
("Research","Geneticists and Genetic resources expert/FGR","Characterize genetic diversity, including nutrition, agronomic, genetic and farmers’ evaluation",23,1),
("Research","Impact assesment specialist","Manage IA component",23,1),
("Research","InVEST modeler",null,23,1),
("Research","Livestock scientist","Develop and implement rangeland management",23,1),
("Research","Market and Marketing expert","Support and manage development of value chains",23,1),
("Research","Nutrition Specialist","Support and manage nutrition education and outputs",23,1),
("Research","Pest and diseases expert","Develop",23,1),
("Research","Policy advisor","Advise on strategies to include and influence policies in implementation guide",23,1),
("Research","Scaling expert","Support the scaling up and scaling out of NPS",23,1),
("Research","Seed system specialist","Develop and manage farmer-led seed systems",23,1),
("Research","Social Scientist","Develop and implement programs to understand factors affecting adoption",23,1),
("Research","Soil biodiversity scientist","Develop and manage monitoring tools for soil biodiversity",23,1),
("Research","Spatial analyst","GIS expert to model and monitor the communities",23,1),
("Research","Value chain expert","Develop value chains and train in rural entrepreneurship",23,1),
("Research","Water resources scientist","Develop water resources conservation and use schemes",23,1),
("Research support","Communication specialist/website developer","Communicate Initiative results and develop web site",23,1),
("Research support","Communications","Support communication ad dissemination of project findings",23,1),
("Research support","Data scientist","Develop data management strategy",23,1),
("Research support","Software engineer and programmer","Conceptualize with researcher user-friendly tools",23,1),
("Research support","Program administration (secretarial support, HR and Finance)","Support initiative implementation and management",23,1),
("Research support","MELIA specialists","Monitor, evaluate and document progress toward outputs and outcomes; indicator frameworks; document learnings and impact (including projections); oversee and support external evaluations reviews (including Scaling Readiness assessments)",23,1),
("Research","Maize Pest & Disease Management; Host Plant Resistance","Initiative Design Team Lead & WP3 Lead;  

Strategy, partnership management and quality control across PHI, together with WP Leads; WP3 implementation, data management; communications & outreach.",19,1),
("Research","Virology, Molecular biologist","Initiative Design Team Deputy Lead & WP1 Lead;  

WP1 implementation; Global diagnostic network and surveillance; data management; partnership management; delivery; communications & outreach.",19,1),
("Research","Germplasm Health; Virology","WP2 Lead; Data management; implementation; partnership management; delivery mainly for WP2, and partly for WP1 & WP3.",19,1),
("Research","Mycotoxin Management","WP4 Lead; Data management; implementation; partnership management; delivery.",19,1),
("Research","Gender Research; MEL","WP5 Co-Lead; Gender and social inclusion strategy, implementation & delivery across PHI; partnership management.",19,1),
("Research","Impact Assessment; MEL","WP5 Co-Lead; MEL & Impact Assessment strategy, implementation & delivery across PHI; partnership management.",19,1),
("Research","Germplasm Health; Virology","WP3-Potato & Sweet Potato IPDM Innovations implementation; delivery; partnership management; partially supports WP3 implementation and delivery.",19,1),
("Research","Banana Pest & Disease Management","WP3-Banana IPDM Innovations implementation; delivery; partnership management",19,1),
("Research","Plant Pathology; Epidemiology","WP3-Potato & Sweet Potato IPDM Innovations implementation; delivery",19,1),
("Research","Legume Pathology;  

Host Plant Resistance","WP3-Legumes & Vegetables IPDM Innovations implementation; delivery; partnership management",19,1),
("Research","Plant Disease Management; Pathology","WP3 IPDM Innovations implementation; delivery; partnership management",19,1),
("Research","Rice Pathology; Host Plant Resistance","WP3-Rice IPDM Innovations implementation; delivery; partnership management",19,1),
("Research support","Mycotoxin Management","WP4 strategy design and implementation; scaling of key innovations under WP4; MEL; partnership management",19,1),
("Research","Wheat disease management; Pathology; Host Plant Resistance","WP5 design; WP4-Mycotoxin mitigation in wheat; WP3-Wheat IPDM innovations implementation and delivery; partnership management.",19,1),
("Research","Post-harvest Processing & Nutritional Quality","WP5 design and implementation; nixtamalization and post-harvest approaches for mycotoxin mitigation; partnership management.",19,1),
("Research","Socio-economics, MEL &  

Impact Assessment","WP5 design and implementation; MEL; impact assessment.",19,1),
("Research","Vegetable IPM","Key innovation and scaling partner for PHI; Co-design and implementation of specific innovations under WP3.",19,1),
("Research","Plant Health Management; Development Communication","Key innovation and scaling partner for PHI; Co-design and scaling of specific innovations under WP1, WP3 and WP5.",19,1),
("Research","IPM; Entomology; 

Impact Assessment; Science Modelling; Data Management","Key innovation and scaling partner for PHI; Co-design and scaling of specific innovations under WP1, WP3 and WP5.",19,1),
("Research","Host Plant Resistance;  

Plant-Microbe Interactions","Co-design of PHI strategy; scaling of PH innovations.",19,1),
("Research","Plant Pathology;  

Plant-Microbe Interactions","Co-design of PHI strategy; scaling of PH innovations.",19,1),
("Research","IPM; Entomology","Key innovation and scaling partner for PHI; Co-design and scaling of PH innovations.",19,1),
("Research support","Administration","Support for administration of PHI activities, including partnership management, capacity building, communications & outreach.",19,1),
("Research support","Financial management","Support for financial management of PHI, including subgrant management.",19,1),
("Research support","Systems perspective, agri-food systems and climate change, partner engagement, CGIAR leadership, fundraising","Initiative lead and co-leadership, assurance of full Initiative delivery",24,1),
("Research support","Admin., financial management, reporting, large, multi-country projects","Admin, financial, reporting, and HR management and quality control",24,1),
("Research support","Multi-stakeholder/audience communications, media coverage, external media","Reporting, media liaison, design of audiovisual materials.",24,1),
("Research","Monitoring system adaptation and implementation, impact assessments.","Reporting, MELIA, data management",24,1),
("Research","Innovation and scaling systems, regional expertise.","Scaling learnings & assessments, WP backstopping",24,1),
("Research","Regional and agrifood systems gender, youth and social inclusion expertise","Lead and ensure gender, youth and social inclusion across all WPs.",24,1),
("Research","Systems agronomy, experiments, participatory action research (PAR)","Design, implement trials, analysis of data, report, publish",24,1),
("Research","Nutrition & food system analysis, diet surveys and adoption pathways","Analysis of data, farm-to-fork mapping",24,1),
("Research",null,"Lead market studies to increase adoption of nutrition-sensitive SET",24,1),
("Research",null,"Design socioeconomic experiments, advise on business models",24,1),
("Research support",null,"Development of the data infrastructure for digitally-enable ecosystems",24,1),
("Research",null,"Generate climate data analysis and develop tailored data per user",24,1),
("Research support",null,"Design implement tailored approaches to deliver based on user needs.",24,1),
("Research",null,"Develop frameworks for achieving both mitigation and development goals",24,1),
("Research",null,"Design approaches for tailoring low emission strategies for diverse next-users",24,1),
("Research",null,"Support the design of profitable low emissions strategies for land use sector",24,1),
("Research",null,"Support and advice the design and implementation of mitigation strategies.",24,1),
("Research",null,"Methodological and implementation support of the InnovHub",24,1),
("Research",null,"Support the development of agronomic and agri-food systems interventions",24,1),
("Research support",null,"Development of farmer market linkage",24,1),
("Research support",null,"Generation of capacities and systemization of knowledge and knowledge networks",24,1),
("Research",null,"Develop, roll out and improve the scaling strategies",24,1),
("Research",null,"Advice and support strategies for achieving policy-oriented outcomes",24,1),
("Research",null,"Support the implementation of policy and investment decision support tools",24,1),
("Research",null,"Develop migration analysis for policy implications for climate goals.",24,1),
("Research",null,"Analyze and extract learnings from the massive datasets generated",24,1),
("Research",null,"Support the development of Sustainable Finance solutions along the value chain",24,1),
("Research",null,"Research leadership, initiative lead and co-leadership, initiative delivery and WPs coordination",25,1),
("Research",null,"Scaling Assessments, WP backstopping",25,1),
("Research",null,"Reporting, MELIA, database management, WP backstopping",25,1),
("Research",null,"Science leadership, coordinating role",25,1),
("Research",null,"Science leadership, coordinating role",25,1),
("Research",null,"Science leadership, coordinating role",25,1),
("Research support",null,"Market and in-country intelligence, stakeholder coordination, policy demand and uptake",25,1),
("Research support",null,"Strategic multi-audience communication, reporting",25,1),
("Research support",null,"Planning and technical/financial reporting",25,1),
("Research support",null,"Project Management Support",25,1),
("Research support",null,"Contractual compliance & partnership agreements",25,1),
("Research",null,"Research leadership, WP lead",25,1),
("Research",null,"Research leadership, WP co-lead",25,1),
("Research",null,"WP data-lead",25,1),
("Research",null,"Data scientist – Post-doc",25,1),
("Research",null,"Impact baseline/assessment",25,1),
("Research",null,"Policy analyst",25,1),
("Research",null,"GIS Specialist, mapping",25,1),
("Research",null,"Country coordinators in Solomon, India, Myanmar, Zamia, Egypt, Nigeria, Cambodia",25,1),
("Research",null,"Data Management and Open Access Officer",25,1),
("Research",null,"2 Research Analysts",25,1),
("Research support",null,"Project support, quality delivery, link between country research team research, corporate services",25,1),
("Research",null,"Each WP country is staffed with a PhD level scientist that coordinates the country-level co-design and implementation of Pathway 1 (RQ2.1) and contributes to Pathway 3 (RQ2.3)",25,1),
("Research",null,"Each WP country is staffed with a PhD level scientist that coordinates the country-level co- design and implementation of Pathway 2 (RQ2.2) and contributes to Pathway 3 (RQ2.3)",25,1),
("Research",null,"Each WP country is staffed with a research team member that implements activities towards Pathway 1 (RQ2.1) and Pathway 2 (RQ2.2)",25,1),
("Research",null,"Synthesis research in WP Pathway 3 (RQ2.3)",25,1),
("Research",null,"Research coordination in Island food systems (Solomon Islands and Timor-Leste)",25,1),
("Research",null,"Research coordination in Bay of Bengal food systems (India and Bangladesh)",25,1),
("Research support",null,"Project support, quality delivery, link between country research team research, corporate services",25,1),
("Research",null,"Co-design of integrated aquatic food system innovation – RQ 1.1.1.; 1.2.1.  

Institutional analysis, support of multi-stakeholder's dialogues – RQ 1.2.1; 1.3.2.",25,1),
("Research",null,"Design and implementation of impact assessments, baseline and follow-up studies, behavioral studies – RQ 1.1.2.; 1.2.2.",25,1),
("Research",null,"Risk and vulnerability mapping – RQ 1.3.1.",25,1),
("Research",null,"Co-design of integrated aquatic food system innovation – RQ 1.1.1.; 1.2.1.",25,1),
("Research",null,"Co-design of integrated aquatic food system innovation – RQ 1.1.1.; 1.2.1.",25,1),
("Research support",null,"Project support, quality delivery, link between country research team research, corporate services",25,1),
("Research",null,"Design and implementation of fish genetic improvement RQ 4.1.1; 4.1.2; 4.1.3.",25,1),
("Research",null,"User trait preferences RQ 4.1.4",25,1),
("Research",null,"Seed system performance RQ 4.2.1",25,1),
("Research",null,"On-farm performance RQ 4.3.1",25,1),
("Research",null,"Impact baseline/assessment RQ 4.3.2",25,1),
("Research support",null,"Project support, quality delivery, link between country research team research, corporate services",25,1),
("Research",null,"Lead WP5 to strengthen national innovation systems",25,1),
("Research",null,"Benefit-cost analysis of candidate innovations packages for scaling (RQ1.1); financial inclusion (RQ2.1)",25,1),
("Research",null,"Based in Solomon Islands, Bangladesh and Zambia to lead field-based learning on designing (RQ1.2), running (RQ2.1) and sustaining (RQ3.1) Aqualabs",25,1),
("Research",null,"Ensuring all analysis is gender-disaggregated and all innovation systems designs and activities involve and engage women, youth and other historically marginalized groups (RQ1.1, RQ1.2, RQ2.1, RQ3.1).",25,1),
("Research",null,"Assess novel feeds and novel species/production systems  to meet demand for affordable, culturally preferred and sustainable aquatic foods and feeds (RQ2.1, RQ3.1)",25,1),
("Research",null,"Identify, evaluate, scale and accelerate innovation in value chain governance and technology to reduce food waste and loss (RQ2.1, RQ3.1)",25,1),
("Research",null,"Scaling institutional and technological innovations in delivering novel nutrition-focused aquatic food products (e.g. in school feeding programs, and in women’s nutrition) RQ2.1, RQ3.1)",25,1),
("Research support",null,"Project support, quality delivery, link between country research team research, corporate services",25,1),
("Research",null,"Integrated resilience research across WPs; Initiative management; global stakeholder engagement",22,1),
("Research",null,"Key research on gender and inclusion across WPs, ensuring uptake in WP workplans and analyses.",22,1),
("Research",null,"Design, implement and evaluate Lean Launch pilots. Guidelines & training material for scaling successful pilots.",22,1),
("Research",null,"Develop and implement MELIA Plans, supporting 6-monthly and annual review & planning meetings",22,1),
("Research support",null,"Coordinate knowledge management plan and functions, incl. OA transfer. Internal and external communications.",22,1),
("Research support",null,"Country operations and stakeholder engagement. Co-convening of policy and technical forums.",22,1),
("Research",null,"Technology adaptation research for UPU vegetable production. Capacity dev. of NARES & partners.",22,1),
("Research",null,"Technology adaptation and delivery for safe and efficient UPU livestock production. Capacity dev. of NARES & partners.",22,1),
("Research",null,"UPU and CRFS studies on food supply and demand, input markets, service sector, labor markets, informal retailing.",22,1),
("Research",null,"New approaches and metrics for strengthening the informal urban food sector.",22,1),
("Research",null,"Knowledge Hub for urban nutrition programming options. UFED tools and metrics.",22,1),
("Research",null,"Urban consumer behavior change strategies and tools.",22,1),
("Research",null,"Adaptive research on key RRR technologies and associated business models.",22,1),
("Research",null,"Food safety analyses, tools for urban food-borne disease estimates, guidelines for urban food safety campaigns.",22,1),
("Research",null,"Develop and pilot PPP models for scaling RRR innovations. Analysis of investment options.",22,1),
("Research",null,"Analysis of (multi-sectoral) UPU governance and policy processes (formal and informal) affecting resilience",22,1),
("Research support",null,"Implement Capacity Dev Plan with partners & stakeholders, incl. e-learning. Documentation of capacity outcomes.",22,1),
("Research",null,"Data collection and analysis, breeding values evaluation, co-develop strategies for the preservation of local genetic resources, co-development of breeding schemes and work on genomics-based selection, support capacity building and scientific production",18,1),
("Research",null,"Reproductive delivery part of the breeding programs represented by artificial insemination, embryo transfer, sires and semen certification, and new generation biotechnologies, support capacity building and scientific production",18,1),
("Research",null,"Establish synergies with GI platform to maintain the forage breeding program for key traits relevant to SAPLING target countries, agronomy of forage production and impacts in the crop-livestock mixed systems; support capacity building and scientific production",18,1),
("Research",null,"Valorization of crop residues and forages in animal feed, feed assessment and formulation, precision feeding, support capacity building and scientific production",18,1),
("Research",null,"Epidemiologist, herd health management, vaccines and disease diagnostics, assessment of priority diseases risk maps, co-creation of herd-health packages, development and delivery of vaccines and diagnostics tools, support capacity building and scientific production",18,1),
("Research",null,"Design and run nutrition sensitive activities with actors and development actors, design monitoring tools, coordinate data analysis, engage in revisions of process based on changes (following ToC), write publications for various audiences., support capacity building of students and partners",18,1),
("Research",null,"Develop and test monitoring tools for women empowerment, coordinate data collection- both qualitative and quantitative, design and run gender approach activities with actors and development actors, design monitoring tools, coordinate data analysis, support capacity building of students and partners",18,1),
("Research",null,"Develop and test value chain analysis protocol and tools, conduct data analysis, write publications, design action research by engaging with actors and agreeing on design for ‘experiments’, design monitoring tools, coordinate data analysis, engage in revisions of process based on changes (following ToC), write publications for various audiences, support capacity building of students and partners",18,1),
("Research",null,"Coordinate ex ante trade off analysis working with the other WPs and stakeholders., work with IA scientists to link ex ante and ex post analysis, improve modelling for livestock master plans working with gender scientists and environment experts from LCSR, contribute to capacity building of next user, write publications",18,1),
("Research support",null,"Lead development and implementation of all communication and knowledge products, including progress toward outcomes and their documentation following ToC",18,1),
("Research support",null,"Coordinate scaling readiness assessments, lead partnership work with WP leads and country coordinators",18,1),
("Research",null,"Finalize impact assessment plan and design IA workplan linked to ToC, lead design of evaluations implemented in the WPs and run some of them, contribute to data analysis, write publications., support MELIA research support staff",18,1),
("Research support",null,"Design monitoring templates, ensure collection of relevant data (quality and timing), data analysis and reporting",18,1),
("Research",null,"Operationalize MELIA system across WPs and countries",26,1),
("Research",null,"Design and implementation of modeling and scenario analysis",26,1),
("Research support",null,"Management and coordination of AMD across WPs and countries",26,1),
("Research support",null,"Support communication and dissemination activities",26,1),
("Research",null,"Establishing Learning alliances to facilitate inclusive social learning around value chain development",26,1),
("Research",null,"Suitability assessment and characterization of agri-production systems based on current biophysical and socio-economic profiles",26,1),
("Research",null,"Improved agronomy at scale using decision enabling advisories and approaches for diversified production system",26,1),
("Research",null,"Developing agri-business models for selected agriculture value chains",26,1),
("Research",null,"Provide analysis to improve nutrition attributes in food systems",26,1),
("Research",null,"Support in developing nutrition sensitive policies, actions, incentives and investments",26,1),
("Research",null,"Qualitative evaluation of changing behaviours of food systems actors",26,1),
("Research",null,"Designing, conducting and analyzing surveys/ ethnographic studies",26,1),
("Research",null,"Cost-benefit analysis and modelling",26,1),
("Research",null,"Coordination with public-private sector value chain (VC) partners, co-designing strategies to reduce VC risks and vulnerabilities",26,1),
("Research",null,"Prioritize and quantify climate risks, support development of improved and inclusive DCAS and bundled services",26,1),
("Research",null,"Development of financing models and partnerships",26,1),
("Research",null,"Support in data collection and analysis",26,1),
("Research support",null,"Lead coordination and project management in country",26,1),
("Research",null,"Support analysis, recommendations, and activities in relation to policy, gender equality, and social inclusion",26,1),
("Research",null,"Promoting inclusive, GESI-informed processes",26,1),
("Research",null,"Strengthening capacity of provincial and local stakeholders",26,1),
("Research",null,"Designing, conducting and analyzing surveys/ ethnographic studies",26,1),
("Research",null,"Modeling and scenario analysis for climate action plans & climate risk vulnerability maps",26,1),
("Research",null,"Development of inclusive climate-responsive delta development pathways, support in knowledge integration network",26,1),
("Research support",null,"Stakeholder coordination in relation to knowledge integration network",26,1),
("Research",null,"Identification, collection of evidence, and analysis of potential recommendation domains for SI innovations for MFS and coordination of piloting and local participatory implementation (WP1, WP3, WP5)",27,1),
("Research",null,"On-ground piloting and participatory/action research for co-design of SI options for MFS (WP3)",27,1),
("Research",null,"Identification, collection of evidence, and analysis of potential recommendation domains for SI innovations for MFS and coordination of piloting and local participatory implementation (WP1, WP3, WP5)",27,1),
("Research",null,"On-ground piloting, data collection, and participatory/action research; integrated management of crop-livestock systems for co-design of SI options for MFS (WP3)",27,1),
("Research",null,"Convening and actor engagement, role-playing games for stakeholder situational analysis, and group buy-in on action research for development (WP3, WP4, WP5)",27,1),
("Research",null,"Spatially explicit quantification and characterization of MFS at regional, national, and subnational levels, identification of development and extrapolation domains (WP1, WP2, WP5); support for MELIA studies and identification of regional and national entry points for SI of MFS (WP1, WP3)",27,1),
("Research",null,"Spatially explicit characterization and analysis of MFS in local geographies; support for MELIA studies and identification of regional and national entry points for SI of MFS (WP2, WP3, WP5)",27,1),
("Research",null,"Methodology development, capacity development, and implementation of gender-transformative approaches at different scales (WPs 1–5)",27,1),
("Research",null,"Local partnership and implementation of gender-transformative approaches for co-design and scaling of socio-technical SI innovations (WP3, WP4)",27,1),
("Research",null,"Analysis of existing supportive and hampering policies for an MFS systems approach, and identification of institutional innovations conducive for an enabling environment and scaling of options for SI of MFS (WP1, WP4, WP5)",27,1),
("Research",null,"Economic analysis of MFS, markets, and value chains, and analysis of performance and trade-offs in SI of MFS (WPs 1–5)",27,1),
("Research",null,"Design and development/implementation of scaling pathways for SI of MFS (WP1, WP4, WP5)",27,1),
("Research",null,"Scaling readiness assessments and development/implementation of local scaling pathways (WP4)",27,1),
("Research",null,"Design, coordination, and overall implementation of capacity development plan (WP5)",27,1),
("Research",null,"Implementation of capacity development strategy at local level (WP5)",27,1),
("Research",null,"Design and implementation of data collection, integration, analysis, visualization, and management strategy (WPs 15)",27,1),
("Research",null,"Data integration and management; support for MELIA in project dashboard development (WPs 1–5)",27,1),
("Research",null,"Design of new and adaptation of existing systems analysis approaches, methods, and tools for description, assessment, and trade off-analysis of MFS at different scales (WP2)",27,1),
("Research",null,"Development and application of systems analysis tools for description, assessment, and trade-off analysis for the co-design of SI of MFS (WPs 1–5)",27,1),
("Research",null,"Development and application of systems analysis tools for qualitative description and assessment of MFS and co-design of SI options and socio-technical innovation packages (WPs 1–5)",27,1),
("Research",null,"Design and implementation of MEL studies and analyses",27,1),
("Research",null,"Design and implementation of IA studies and update of benefits projection",27,1),
("Research support",null,"On-ground logistics and implementation of activities, data collection, reporting, and follow-up of local partnerships for co-design and scaling SI options for MFS (WP3, WP4, WP5)",27,1),
("Research support",null,"Strategic communication and knowledge management including support to publications (WPs 1–5)",27,1),
("Research support",null,"Development and deployment of information and communication technologies for communicating and scaling of socio-technical SI innovation packages (WP4)",27,1),
("Research",null,"Initiative lead and co-leadership, assurance of full Initiative delivery",9,1),
("Research support",null,"Admin, financial, reporting, and HR management and quality control",9,1),
("Research support",null,"Reporting, MELIA, database mgt.",9,1),
("Research support",null,"Reporting, multi-audience communication",9,1),
("Research support",null,"Scaling Assessments, WP backstopping",9,1),
("Research support",null,"Lead and assure research and scaling in GESI across WPs",9,1),
("Research support",null,"Assemble & analyze datasets, develop integrated databases (RQ 1)",9,1),
("Research support",null,"Develop indicator framework, build and maintain databases (RQ 2)",9,1),
("Research support",null,"Develop data use cases, support policy and practice partners in evidence uptake and scaling partnerships (RQ1,2)",9,1),
("Research support",null,"Design, implement trials, analysis of data, report, publish (all RQs)",9,1),
("Research support",null,"Farm and landscape-level modeling, reporting, publishing (RQ1,2)",9,1),
("Research",null,"Design social experiments, advise on business models (RQ 1,2,3)",9,1),
("Research",null,"Landscape-level research in WP2 (RQ2), contribution to WP5 (RQ1)",9,1),
("Research",null,"Business model development, assure PPPs, report, publish (RQ3)",9,1),
("Research",null,"Research design analysis of data, report, publish (RQs 1,2,3)",9,1),
("Research support",null,"Design & lead VSM research, partner mgt., report, publish (RQ 2)",9,1),
("Research support",null,"Design & lead retain environment research, report, publish (RQ 3)",9,1),
("Research support",null,"Analyses of data on current diets, plate-to-farm mapping (RQ 1)",9,1),
("Research support",null,"Design, implement, analyze, publish dietary determinants (RQ 1)",9,1),
("Research support",null,"Design and implement research on BCC interventions (RQ 2)",9,1),
("Research support",null,"Support partner: cost of diet & other affordability analyses (RQ 1,3)",9,1),
("Research support",null,"Coordinate research reviews, ecological food print modeling (RQ 1)",9,1),
("Research support",null,"Assist ecological food print modeling (RQ 1), support WP 2 R Q2",9,1),
("Research support",null,"Oversee, report and publish social experiments, RCTs (RQ 2,3,4)",9,1),
("Research support",null,"Research co-design support, analysis, publishing (RQs 1,2,3,4)",9,1),
("Research",null,"Design, oversight and implementation, management of research, analysis and documentation, delivery",10,1),
("Research",null,"Design research on mechanization, management of research, scientific knowledge, publication",10,1),
("Research",null,"Design, implementation, management of research, scientific knowledge, publication",10,1),
("Research",null,"Adoption monitoring, impact assessment, scientific knowledge, delivery, publication",10,1),
("Research",null,"Scientific knowledge, delivery, publication",10,1),
("Research",null,"Scientific knowledge, delivery, publication",10,1),
("Research",null,"Management of research, knowledge",10,1),
("Research support",null,"MEL",10,1),
("Research support",null,"Publication, documentation, and delivery",10,1),
("Research support",null,"Designing bundles of agro-advisories and ARM",10,1),
("Research",null,"Climate impacts analysis",10,1),
("Research support",null,"Designing insurance products",10,1),
("Research support",null,"Designing risk-informed credit",10,1),
("Research support",null,"Impact Assessment and economic analysis",10,1),
("Research support",null,"Leading design of mobile systems",10,1),
("Research support",null,"Link between research and operations",10,1),
("Research support",null,"Design of research, implementation, management of research, quality control, publications, delivery, design of investment products, partnerships",10,1),
("Research support",null,"Scientific knowledge/Technical assistance (TA), delivery",10,1),
("Research support",null,"Scientific knowledge (TA), delivery",10,1),
("Research support",null,"Scientific knowledge (TA), delivery",10,1),
("Research support",null,"Scientific knowledge (TA), delivery",10,1),
("Research support",null,"Scientific knowledge (TA), delivery",10,1),
("Research support",null,"Adoption monitoring, impact assessment, scientific knowledge, delivery, publication",10,1),
("Research support",null,"Design of research and implementation on ecosystem and solution space",10,1),
("Research support",null,"Environmental impact assessments",10,1),
("Research support",null,"Crop water modelling",10,1),
("Research support",null,"Integrated impact modelling of the impact of climatic risks, and adaptation and mitigation strategies, on inter-regional trade patterns",10,1),
("Research support",null,"Evidence to support SI/diversification policy implementation, and development of policy monitoring frameworks",10,1),
("Research support",null,"Policy hub development, policy coherence assessments",10,1),
("Research support",null,"Policy dialogue, institutional coordination",10,1),
("Research support",null,"Scientific knowledge, delivery,",10,1),
("Research",null,"Publication, documentation, and delivery, Advocacy",10,1),
("Research",null,"Big data platform developments",10,1),
("Research support",null,"Provide conceptual depth and clarity; establish and strengthen mixed methods that bring cutting edge GESI focus.",10,1),
("Research support",null,"Provide the NR interface with Sustainable Inclusive Agrifood Systems; capacity for systems change that leads to gender transformative social inclusion",10,1),
("Research support",null,"Design, plan and execute collaborative partnerships with public, private and grassroots actors and initiatives",10,1),
("Research support",null,"Training design, delivery, evaluation.",10,1),
("Research support",null,"Translate and repackage research into policy-relevant and widely accessible science outputs.",10,1),
("Research support",null,"Lead the ESA Scaling Hub, ensure integration and collaboration and co-investment across CGIAR Initiatives, high level demand-supply alignment",10,1),
("Research support",null,"Lead the ESA scaling science (e.g. innovation and scaling network analysis, review of scaling cases)",10,1),
("Research support",null,"Lead ESA scaling practice (e.g. develop scaling partnerships, co-investments in scaling, support scaling strategy implementation, etc.)",10,1),
("Research support",null,"Support science and practice of scaling innovation in ESA",10,1),
("Research",null,"Initiative Lead (Coordinator) and Co-Lead (Resource Mobilization). 

 

Other Research: MELIA Economist (shared with WP5); Communication. Policy and Partnership Specialist (CORAF position)",28,1),
("Research support",null,"Accountant and Executive Secretary.",28,1),
("Research",null,"Lead: Systems agronomist. 

 

Other Research: Plant health expert; Crop production expert; Inland fish farming expert; Seed systems expert; and Nutritionist.",28,1),
("Research",null,"Lead: Climate-change scientist. 

  

Other Research: Digital systems specialist; Digital Information Management Expert; Climate, pest and disease modeler. Business impact & sustainable finance originator; Human centered design specialist and a Product management & innovation specialist.",28,1),
("Research",null,"Lead: Governance Expert. 

 

Other Research: Land and water resources modeler; Water resources specialist; NRM Expert; Social Scientist; Gender scientist; Knowledge Management Expert (shared time); One-Health Expert.",28,1),
("Research",null,"Lead: Agricultural Economist/agribusiness specialist 

 

Other Research: Gender and Youth Development and Vocational Training Expert; Value chain and market access expert; Innovation platform and Institutional (3P) Expert; Digital Information management expert; Post harvest Expert; Policy Support Expert.",28,1),
("Research",null,"Lead: Technology and Innovation Scientist. 

  

Other Research: Knowledge Management Expert. 

Behavioral Change Specialist; Data Management Specialist; MELIA Specialist (part-time) Innovation Scaling.",28,1),
("Research",null,"The gender, social equity, inclusion and governance team has the experience and capabilities to:  

i) Go beyond gender and social inclusion to embrace a more radical social equity agenda that addresses the root causes of vulnerability rather than the immediate causes of vulnerability.  

ii) Use the Gender and Social Equity Framework to guide ClimBeR’s work internally and with external partners to build resilience, foster a social transformation and minimize the dangers of maladaptation. 

iii) Analyze success and failures to provide guidance on design and implementation of transformative projects. 

iv) Perform policy, institution, and governance analysis to identify gaps, potential opportunities to cross-scale cooperation in building systemic resilience for transformative adaptation.",17,1),
("Research",null,"The scaling and innovation team has the experience and capabilities to:  

i) Strengthen the linkages between evidence, policy and practice in order to support scaling up and out of research products emerging from ClimBeR’s four Work Packages and two cross-cutting themes. 

ii) Build interdisciplinary teams and transnational partnerships in the spheres of control, influence and interest; iii) Locate ClimBeR at the center of emerging scaling and innovation theory and practice e.g. working with Institute of Development Studies (IDS); Wageningen University; Collaborating for Resilience; Belmont Forum; and Global community of practice on scaling development outcomes. 

iv) Promote wider multiscale cooperation among public and private partnership for scaling of adaptation interventions through business models",17,1),
("Research",null,"The AFRICAP iFEED team has been collaborating for 4 years on this topic and will develop and apply methods focused on climate variability and extremes. The team consists of senior experts in climate science, crop-climate modelling, nutrition security, trade, and policy engagement. This team is complemented by the Disruption for Transformation Team which builds upon 8 years of scenario guided policymaking in 6 global regions under CCAFS.",17,1),
("Research",null,"The climate risk team is a multidisciplinary group, including agricultural insurance experts, climate risk analysts, meteorologists, agricultural economists in impact assessment, farming system experts, geospatial analysis specialists, specialists in digital platforms, agricultural extension specialists and nutritionists. In relation to digital tools this team has the experience and capabilities to: 

i) Promote digital inclusivity across scale and sectors using technologies, tools, models and platforms to ensure bottom-up approaches for developing resilience strategies towards transformative adaptation. 

ii) Analyze gaps and potentials for using digital tools by partners in monitoring targets/ indicators for resilient development goals.",17,1),
("Research",null,"A multi-disciplinary team, including senior and junior economists, qualitative data and big data analysts, spatial analysts (Evidence 4 Climate Security), peace and security studies experts and analysts (Programming 4 Climate Security), senior and junior policy experts and data analysts (Policy 4 Climate Security) and financial experts and data analysts (Finance 4 Climate Security).",17,1),
("Research support",null,"ClimBeR’s support research team has the experience and capabilities to: 

 i) Support the translation from research to policy practice and outreach for wider stakeholders. 

ii) Document success stories and evidence of investment, scaling and impact.  

iii) Develop and implement communication tools and approaches that contribute to ClimBeR’s outcomes, One CGIAR’s PRMF, that generate positive change, and that at the same time promote ClimBeR’s science, inform major policies and programs, make knowledge open access, and encourage learning and sharing of information across the Initiative and with partners.",17,1),
("Research",null,"Initiative and Work Package planning, implementation, and reporting",29,1),
("Research",null,"Facilitation of engagement processes with national and regional partners",29,1),
("Research",null,"Lead development of key research questions and corresponding scenario development with national partners, donors, and researchers",29,1),
("Research",null,"Development and application of economic modeling tools for integrated simulation analysis of FLW system interactions at multiple scales",29,1),
("Research",null,"Development and application of economic modeling tools for integrated simulation analysis of FLW system interactions at multiple scales",29,1),
("Research",null,"Econometric analysis to complement and support integrated foresight analysis",29,1),
("Research",null,"Development and improvement of links to relevant climate, biodiversity, ecosystem service, and pest-and-disease models as needed for integrated foresight analysis",29,1),
("Research",null,"Development and improvement of links to relevant crop, livestock, and fish models as needed for integrated foresight analysis",29,1),
("Research",null,"Development and improvement of land use and hydrological models and associated system metrics as need for integrated foresight analysis",29,1),
("Research",null,"Development and implementation of theme-specific spatial analyses in support of different domain priorities",29,1),
("Research",null,"Demand-driven quantitative and statistical analysis of large data sets to enhance understanding of FLW system processes and outcomes",29,1),
("Research",null,"Development and maintenance of foresight focused databases and knowledge repositories",29,1),
("Research",null,"Developing system-level metrics related to the One CGIAR impact areas in collaboration with thematic specialists",29,1),
("Research",null,"Coordinate implementation of the M&E plan with Initiative and WP leads",29,1),
("Research",null,"Impact assessment analysis in coordination with Initiative and WP leads",29,1),
("Research",null,"Implementation of scaling readiness assessments in coordination with Initiative and WP leads",29,1),
("Research",null,"Development and delivery of in-person and online training materials and programs",29,1),
("Research",null,"Facilitate knowledge sharing among and beyond Initiative partners",29,1),
("Research support",null,"Support Initiative leadership in day-to-day operation and reporting; track deliverables and budget",29,1),
("Research support",null,"Development, maintenance and updating of the Foresight web portal",29,1),
("Research support",null,"Editorial, design, and publication support",29,1),
("Research support",null,"Support Initiative leadership and program management in administrative duties including sub-contracts and budget monitoring",29,1),
("Research",null,"Economic policy modeling, cost/benefit analysis, causal impact analysis, multi-market modeling.",30,1),
("Research",null,"Gap assessment (data, information, supporting system), evaluating digital technology impacts on outcomes.",30,1),
("Research",null,"Identifying the roles of women and youth and assessing the potential of digital technologies to address challenges.",30,1),
("Research",null,"Assessing the sampling frames for real-time data collections and addressing data quality issues.",30,1),
("Research",null,"Developing a workflow of satellite remote sensing data acquisition, processing, identifying system-level anomalies.",30,1),
("Research",null,"Processing geospatial, ground truth, historical (secondary) data to inform impact evaluation, policy analysis, analytics.",30,1),
("Research",null,"River basin-level integrated modeling to simulate climate-driven dynamics between food, water, land, energy, biodiversity systems.",30,1),
("Research",null,"Landscape-level water balance and accounting to support the sustainable allocation of water resources across sectors.",30,1),
("Research",null,"Spatially-explicit integrated modeling of distributed water resource, infrastructure, management options and economic values.",30,1),
("Research",null,"Analyzing historic climatology to assess risks and incorporating subseasonal climate forecasts into system dynamics modeling.",30,1),
("Research",null,"Assessing the changes in food productivity and profitability under the scenarios of subseasonal climate, water, and market changes.",30,1),
("Research support",null,"Guiding the process of improving local digital ecosystems based on the analysis of human-technology interactions at multiple levels.",30,1),
("Research support",null,"Ensuring the collection, management, and sharing of data with partners are ethical and securely conducted.",30,1),
("Research support",null,"Supporting data cleaning, annotation, harmonization, documenting, and publishing for reproducible science and research .",30,1),
("Research support",null,"Supporting the rapid visualization of large real-time datasets for detecting anomalies and timely informing decision-makers.",30,1),
("Research support",null,"Provision of training to raise digital capabilities for finding, interpreting, and using timely information for decisions.",30,1),
("Research",null,"Research gender transformative approaches to change normative constraints to women’s full participation in the AFS to build economic resilience (WP1). 

Conduct intersectional analysis of challenges to uptake of STIBS and track processes and outcomes of implementation of STIBs (WP2). Test how social protection programs and complementary interventions strengthen women’s climate resilience (WP3).  Identify how to overcome policy implementation challenges which impede participation and voice for women (WP4).",31,1),
("Research",null,"Analyse gender and climate data linked to existing data from RCTs of social protection programs and complementary interventions (WP3). Analyse impact of program on women’s climate resilience. Test how social innovations, organizational strategies, and policies affect women’s voice and benefits from AFS governance (WP4).",31,1),
("Research",null,"Co-design pilot RCT and evaluate innovations on the impact of STIBs on gender equality and women’s empowerment for resilience (WP2). Design pilot RCT with existing partners to test how cash transfers promote women’s take-up of climate adaptation strategies (WP3). Design pilot RCTs of interventions to raise women’s voice and agency in governance (WP4). Conduct evidence reviews about how social protection affects women’s well-being during climate shocks and stressors (WP3), and about barriers, innovations and policies to improve women’s voice and agency (WP4).",31,1),
("Research",null,"Design and conduct qualitative assessments on how women perceive the role of social protection in supporting them to mitigate and adapt to effects of CC, as well as explore remaining gender barriers for future programming to address (WP3). Assess what are policy implementation challenges and how policies and innovations influence prevailing gender norms (WP4).",31,1),
("Research support",null,"Support design and implementation of mixed-methods evaluations of GTAs, with other CGIAR Initiatives and other partners, to generate emerging lessons (WP1). Use outcome mapping and multistakeholder approaches to design and monitor processes and outcomes including capacity for designing and implementing STIBs (WP2).",31,1),
("Research support",null,"High-quality research support for quantitative analysis: Support study designs, manage data collection and support analysis of quantitative data from RCTs (WP1-WP4).",31,1),
("Research support",null,"Develop novel communications products such as guidelines, webinars and video stories for use by AFS stakeholders to design, implement, evaluate and scale GTAs (WP1), and to provide as on-line repositories of databases and tools for designing and implementing STIBs (WP2). Organize stakeholder workshops, support development of communication products such as policy briefs, webinars, and other from research products (WP3-WP4).",31,1),
("Research",null,"Lead and Co-Lead the Initiative: Strategic research design, partner engagement",16,1),
(null,null,"Research Coordination, planning, and reporting",16,1),
(null,null,"Planning and implementation of specific WPs",16,1),
(null,null,"Leading country implementation, ensuring coherence of work packages, coordinating with local partners, and convening quarterly meetings of country teams and work package leads.",16,1),
("Research",null,"Lead policy analysis, development of tools, policy engagement strategy",16,1),
(null,null,"Use of modeling tools, scenario analysis, investment prioritization",16,1),
(null,null,"Analysis of political economy, barriers and enablers of policy and program implementation, Evaluation of investment programs, impact evaluation design for new investment programs with governments, funders, private sector",16,1),
(null,null,"CoPP, regional learning",16,1),
("Research",null,"Design of capacity development strategy, lead capacity development activities, evaluate capacity, link with capacity development partners in country, regional and globally",16,1),
(null,null,"Research Analysts",16,1),
(null,null,"Data management, analysis",16,1),
(null,null,"Provide communication support to all Initiative activities",16,1),
(null,null,"Lead M&E activities",16,1),
(null,null,"Support knowledge management and synthesis",16,1),
("Research",null,"Co-design, development and management of research activities and innovation; integrated WEFE assessments; quantitative and qualitative field experiments (incl. design, data collection, analysis); scaling; knowledge synthesis; cooperation with partners to support policy and decision-making process; outreach and science-policy activities",15,1),
("Research support",null,"Co-design leadership program (WP5), manage program in partnership with academic partners as well as demand, innovation and scaling and partners; support learning materials (external) and internal learning/development processes",15,1),
("Research support",null,"Monitor, evaluate and document progress toward outputs and outcomes; indicator frameworks; document learnings and impact (including projections); oversee and support external evaluations reviews (including Scaling Readiness assessments)",15,1),
("Research support",null,"Set up and manage internal comms among and between teams and stakeholders; manage comms for reporting, mass media and digital comms (social media, websites); support researchers with writing, editing, copyright issues, etc.",15,1),
("Research support",null,"Secretarial support of Initiative implementation (staff, consultants, investments); organization of meetings and support of Initiative management and governance; oversee procurement and compliance",15,1),
("Research",null,"Lead and/or conduct research on market trends, market concentration and efficiency, trade integration, price discovery, and income distribution in agrifood markets",14,1),
("Research",null,"Lead and/or conduct research on modeling tools to assess tradeoffs, policy scenarios, agricultural and food subsidies reform; focal point for links to Foresight and Metrics initiative",14,1),
("Research",null,"Lead and/or support research on the influence of the policy environment on value chain structures and performance; identify policy levers for maximizing impact.",14,1),
("Research",null,"Lea and/or support development and application of analytical tools for value chains including work on governance and business models tools",14,1),
("Research",null,"Lead and/or support engagement with private sector around innovations in value chain organization and business models and analysis for design, implementation and assessment of business models in agrifood sectors",14,1),
("Research",null,"Lead and/or support engagement with private sector and public agencies and undertake assessments of effectiveness of innovations in food quality upgrading, standard setting, and certification. Focal point for links with SHIFT initiative",14,1),
("Research",null,"Lead and/or conduct research on digital platforms for logistics and inclusive business models for logistics services",14,1),
("Research",null,"Lead and/or conduct research on digital financial services,",14,1),
("Research",null,"Lead and/or support gender research, ensure gender research questions are incorporated into study designs; support use and development of Women’s Empowerment in Agriculture Index for Market Inclusion and similar tools; focal point for HER+ and CGIAR Gender Platform",14,1),
("Research",null,"Lead and/or support youth focused research and provide support to assess impact of innovations on youth",14,1),
("Research",null,"Research on food security impacts of innovations, focal point for SHIFT",14,1),
("Research",null,"Lead and/or conduct research on incorporation of emissions scenarios and climate modeling into economic modeling tools; lead assessment of impact of innovations on climate and natural resource indicators; focal point for MITIGATE and CLIMBER initiatives",14,1),
("Research",null,"Lead and/or support to (a) quantitative research for robust statistical design and analysis; (b) qualitative methods for robust design and analysis; (c) support application of novel approaches to supply chains and markets including spatial analysis, big data approaches, discourse analysis and others.",14,1),
("Research",null,"Lead or support initiative level MEL and IA strategies and studies; design rigorous, initiative appropriate impact assessments to test ToC causal logic and assumptions; focal point for SPIA and One CGIAR MELIA entity.",14,1),
("Research",null,"Review plans for or support causal impact assessments to identify ways to maximize benefits for as well as appropriately measure impacts on women’s economic empowerment",14,1),
("Research",null,"Lead and/or support scaling readiness including innovation profiling, innovation package design, scaling readiness assessments, and scaling strategies",14,1),
("Research",null,"In-country stakeholder engagement and partnerships for impact",14,1),
("Research",null,"Data management, data analysis, data collection, supervision of field work, etc.",14,1),
("Research support",null,"Support initiative communications presence including in social media, with major stakeholders and within CGIAR; provide support for publications, manage branding guidelines.",14,1),
("Research support",null,"Develop web-based interface for Knowledge Platform (KISM), organize web-based stakeholder dialogues, make knowledge products accessible and sharable, etc.",14,1),
("Research support",null,"Manages key databases for Knowledge Platform, AFED global database and other key databases generated and used by the Initiative",14,1),
("Research",null,"Genebank management, Initiative, and Work Package leaders",4,1),
("Research",null,"Plant Genetic Resources Policy: policy research, engagement with international policy bodies",4,1),
("Research",null,"Crop curators, genetic resources characterization, subsetting, diversity analysis",4,1),
("Research",null,"Germplasm Health – coordinator, unit leaders, specialist staff on diagnostics research, controls, disease cleaning",4,1),
("Research",null,"Seed quality and data management, workflow management, germplasm documentation",4,1),
("Research",null,"Genebank operations: seed lab, viability monitoring",4,1),
("Research",null,"Genebank operations: in vitro",4,1),
("Research",null,"Genebank operations: field bank management, accession characterization, seed regeneration",4,1),
("Research",null,"Genebank operations: cryopreservation expertise on protocol development, cryobanking technicians",4,1),
("Research",null,"Design and management of qualitative research and large surveys and evaluations (WP1–2): selection and recruitment of data collection firms; development of study protocols, survey/ qualitative instruments and training manuals; training and supervision of field staff. 

Co-design and evaluation of innovations targeted to consumers and FEs (WP1–2): design, implementation, and analysis of data from rigorous evaluations using experimental designs. 

Data management and analysis; publication of peer-reviewed papers, briefs, slide decks; communication/dissemination.",13,1),
("Research",null,"Implementation of national political economy analysis and critical discourse analysis (WP3) on food system transition/ transformation.  

Design, field-testing, and implementation of consensus building techniques with (sub)national stakeholders (WP3–5). 

Data management and analysis; publication of peer-reviewed papers, briefs, slide decks; communication/dissemination.",13,1),
("Research",null,"Design and Implementation of modeling and scenario analyses (WP4); data management and analysis; publication of peer-reviewed papers, policy briefs, slide decks. communication/ dissemination.",13,1),
("Research",null,"Contribution to WP1–5 to incorporate gender, youth, and inclusion in all research programs. 

Design and implement a SHiFT-specific research agenda and program on gender, youth, and inclusion.",13,1),
("Research support",null,"Management and coordination of SHiFT program across WPs and countries; support to SHiFT leadership team and partners; planning and tracking outputs and outcomes and support to MELIA; support to team and partner meetings, etc.",13,1),
("Research support",null,"Research support for field-work planning and implementation; design of evaluations; enumerator training; data management, and analysis; publications and dissemination of results",13,1),
("Research support",null,"In-country engagement (local staff) (WP1–5) (possibly supported by in-country international staff from One CGIAR): facilitate engagement with stakeholders in country; help identify research firms; support in-country communication and dissemination of results; support partnerships, etc.",13,1),
("Research support",null,"Research support for (sub)national and global data gathering, compiling, management, and (modeling/econometric) analysis; publications and dissemination of results.",13,1),
("Research support",null,"Research support for engagement with and capacity building of subnational and national food system stakeholders and key actors; analysis publications and dissemination of results.",13,1),
("Research support",null,"Support all communication and dissemination activities for SHiFT internationally and a country and regional level (linking with local staff).",13,1),
("Research support",null,"Support all MEL activities across WPs and countries",13,1),
("Research support",null,"Support all SHiFT’s administrative and financial work and reporting",13,1),
("Research",null,"Initiative Lead - Initiative planning, implementation, reporting.",12,1),
("Research",null,"Deputy lead - Supports Initiative coordination and reporting",12,1),
("Research",null,"Process manager - Supports Initiative leadership in the day-to-day operation and reporting",12,1),
("Research",null,"Supports Initiative leads in administrative aspects (sub-contracts and budget monitoring, logistic support)",12,1),
("Research",null,"Leads the implementation of the MELIA plan in coordination with WP Leads",12,1),
("Research",null,"Implements Scaling Readiness Assessments in coordination with Initiative and WP leads",12,1),
("Research",null,"WP1 Lead - Participatory research processes and International ALL Network Coordination",12,1),
("Research",null,"Country coordinator of ALL:  Multi-stakeholder participatory processes, participatory methods, stakeholder engagement",12,1),
("Research",null,"Junior expert on participatory research methods, data collection",12,1),
("Research",null,"Research assistant -data consolidation, secondary information collection, field work",12,1),
("Research",null,"Mid-career Agronomist - Co-design of agroecological practices in targeted agricultural systems",12,1),
("Research",null,"Mid-career Economist - Support co-design of agroecological practices with economic analyses",12,1),
("Research",null,"Research assistant - Consolidation of information to assist co-design of agroecological practices",12,1),
("Research",null,"Mid-career scientist - Co-design of agroecological practices in livestock systems (in Burkina Faso and Tunisia)",12,1),
("Research",null,"Mid- career scientist - Forages management, co-design of agroecological practices (for Tunisia and India)",12,1),
("Research",null,"WP2 Lead (and co-lead tbd)- Multidisciplinary experts in indicator/metrics development, application, and tradeoffs analyses",12,1),
("Research",null,"Senior expert in development of metrics to assess productivity factors, expert on agroecological practices",12,1),
("Research",null,"Senior expert, economic performance assessments (for agricultural practices, business models)",12,1),
("Research",null,"Assessment framework and metrics for gender, livelihoods, and social inclusion",12,1),
("Research",null,"Hydrological assessments, water balances, water footprints with and without agroecological practices",12,1),
("Research",null,"Design of soil health assessments protocol, indicators, and metrics",12,1),
("Research",null,"Design of metrics for (agro)biodiversity assessments, strategies for diversifying systems",12,1),
("Research",null,"Environmental modeling across scales of effects of agroecological innovations in water, land, ecosystem services",12,1),
("Research",null,"Co-design of strategies to manage trees in diversified systems, agroforestry systems",12,1),
("Research",null,"Agent-based modeling to understand changes in stakeholders’ interactions and decisions",12,1),
("Research",null,"Expert in household-level diet diversity assessments",12,1),
("Research",null,"Junior scientist for the application of holistic assessment framework in each ALL (x 7)",12,1),
("Research",null,"Research assistant - agronomic assessment of agroecological practices in each ALL (x 7)",12,1),
("Research",null,"Research assistant - preparation of environmental modeling input data in each ALL (x 7)",12,1),
("Research",null,"Research assistant - data collection and analysis of survey data for economic indicators estimation in each ALL (x 7)",12,1),
("Research",null,"Research assistant - data collection and analysis of performance of productivity data in livestock systems in each ALL (x 7)",12,1),
("Research",null,"WP 3 Lead. Oversees and guides value chain and business models analyses across ALLs",12,1),
("Research",null,"WP 3 Co-lead -Financial analyses and investment cases",12,1),
("Research",null,"Economic analyses for co-design of business models",12,1),
("Research",null,"Guide mainstreaming and evaluation of gender and social inclusion indicators in business models and financial strategies",12,1),
("Research",null,"Junior scientist - Workshop organization and implementation for value chain analyses and business models co-design (1 per ALL)",12,1),
("Research",null,"Data collection and analyses of economic and financial indicators of business models and investment cases (1 per ALL)",12,1),
("Research",null,"Participatory methods application for value chain analyses and business models co-design (1 per ALL)",12,1),
("Research",null,"Estimation of environmental benefits of agroecological business models and investment cases (1 per ALL)",12,1),
("Research",null,"Financial analyses and investment cases for livestock-based business models (Burkina Faso and Tunisia) (1 per ALL)",12,1),
("Research",null,"WP4 Lead - local institutions and governance",12,1),
("Research",null,"WP4 Co-lead: public policy analysis",12,1),
("Research",null,"Coordination and implementation of multistakeholder platforms in ALLs (1 per ALL)",12,1),
("Research",null,"Evidence based reports for policymakers (1 per ALL)",12,1),
("Research",null,"Policy and governance structures analyses (1 per ALL)",12,1),
("Research",null,"Assessments of effects of scaling agroecological innovations in national socio-economic and environmental goals",12,1),
("Research",null,"WP5 Lead: Design, plan, and guide implementation of participatory and iterative learning methods; collective action processes",12,1),
("Research",null,"WP5 Co-Lead: Plans and guide implementation of social inclusion, gender, agency, and behavior change analyses",12,1),
("Research",null,"Junior expert, coordinates application of participatory research and innovation co-design methods (1 per ALL)",12,1),
("Research",null,"Support qualitative and quantitative data for behavioral change analyses",12,1),
("Research",null,"Support implementation of workshops, data collection, cleaning, and consolidation",12,1),
("Research",null,"Expert on workshop and focus group facilitation; coordination of enumerator/interviewer field teams (1 per ALL)",12,1),
("Research",null,"Qualitative research and data management, experienced in agency and behavior change methods",12,1),
("Research",null,"Agent-based modeling",12,1),
("Research",null,"Initiative leadership",7,1),
("Research",null,"Lead work package research in multiple sites",7,1),
("Research",null,"Lead country research and engagement with stakeholders",7,1),
("Research",null,"Lead field teams in WP 2 and WP 3",7,1),
("Research",null,"Lead field teams in WP 3 and WP 4",7,1),
("Research",null,"Implement research in WP1",7,1),
("Research",null,"Implement research in WP1",7,1),
("Research",null,"Planning, GHGI",7,1),
("Research",null,"Participatory research",7,1),
("Research",null,"Participatory research",7,1),
("Research",null,"Markets/commodities",7,1),
("Research",null,"Policy research - enabling conditions",7,1),
("Research",null,"Support field components of the research",7,1),
("Research",null,"Support GIS/remote sensing research",7,1),
("Research support",null,"Support project management",7,1),
("Research support",null,"Support project management",7,1),
("Research support",null,"Lead WP5 implementation",7,1),
("Research support",null,"WP5 implementation",7,1),
("Research support",null,"MEL implementation",7,1),
("Research",null,"Consumer Behavior WP1 will design and manage causal impact assessments to understand how to increase F&V intake through behavioral approaches, working closely with WP5 and WP6. Accountable for design and implementation of pilot studies that leverage behavior and food-related programs/policies to increase F&V intake – including testing innovative new behavioral approaches and product development. Accountable for data management, analysis and dissemination.",32,1),
("Research",null,"Breeding, Genetic Innovations, and Sustainable Seed Systems WP 2 has a social equity focus in support of creating accessible, affordable, and sustainable seed systems. Accountable for design and implementation of trials, analysis of data, and support of dissemination of results. Outputs include breeding tools, seed cultivars, and outreach products. Will support eco-agro landscape analysis with WP 3.",32,1),
("Research",null,"Safe and Sustainable Production Systems WP3 is accountable for design and adaptation of equity focused approaches to safe and sustainable F&V systems. Will deliver technological packages to reach farmers for large scale adoption. With WP2, will conduct agro-eco landscape analysis, to ensure that approaches are climate resilient and promote biodiversity of both farming systems and their environment.",32,1),
("Research",null,"Post Harvest and Inclusive Market WP4 will focus on understanding and addressing postharvest losses and the standardization of food safety best practices, with a focus on social equity and job creation. Accountable for collaborating with internal/external partners on design and implementation of (1) context appropriate technology packages to reduce post-harvest losses and (2) technical and culturally appropriate food safety technologies/measures, the analysis of trial data, and scaling of technology. Work closely with WP3",32,1),
("Research",null,"Food Environments WP 5 Will design and implement affordability studies, GIS assessments, and qualitative work around food environment barriers to F&V accessibility and affordability. Will co-design impact assessments with partners to understand how innovations affect food environments in relation to fruits and vegetables and how social protection programs can be leveraged to increase F&V intake. Will collaborate with WP6 on political economy analysis.",32,1),
("Research",null,"Enabling Environments WP6 is accountable for analysis of local and national political economy as related to the political, social, and economic drivers of F&V consumption. Accountable for designing collaborative mechanisms/platforms for generating demand for evidence and facilitating capacity strengthening for all levels of governance. Will collaborate with all WPs.",32,1),
("Research support",null,"Management and coordination of FRESH Initiative across WPs. Accountable for tracking outputs and outcomes, providing support to MELIA and communications teams. Will provide direct support to FRESH leadership and partners.",32,1),
("Research support",null,"Support FRESH communications, outreach, and dissemination events at local and regional levels. Communications expert will provide support in translation of research into policy practice (WP6) and for wider stakeholders (WP1-5). Accountable for communications across multiple mediums (website, social media), and reporting.",32,1),
("Research support",null,"Accountable for support of all FRESH administrative, financial, and contracting work.",32,1),
("Research support",null,"Support FRESH WPs in the design and delivery of capacity building-related activities. Accountable for identifying opportunities for shared capacity development interventions, ensure technical excellence in interventions delivered, and support the tracking of capacity strengthening across WPs. Together with WP6 and the communications expert, responsible for facilitating capacity strengthening and generating demand for evidence for policy makers at national, sub-national and local levels.",32,1),
("Research",null,"Assess and scale technologies (WP1, 2)",11,1),
("Research",null,"Social economy, modelling and policy research (WP2, 5)",11,1),
("Research",null,"Participatory approaches (WP 1, 5), Cost-benefit & tradeoff analysis (WP1 2,5)",11,1),
("Research",null,"Intrahousehold burdens and benefits of technologies (WP2)",11,1),
("Research",null,"Development and testing of adaptation tracking protocols (WP5)",11,1),
("Research",null,"Cost-benefit analysis for investment (WP4)",11,1),
("Research",null,"Assess key performance indicators; design instruments (WP4)",11,1),
("Research",null,"Multidisciplinary team develops data, analyses, guidelines, software systems and institutional engagement for climate security (WP1,3,5)",11,1),
("Research",null,"Design inclusive DSTs, services, and technologies (WP1,2,3).",11,1),
("Research",null,"Technologies in practice and social inclusion mechanisms (WP1,2,3)",11,1),
("Research",null,"Socio-economic heterogeneity in production landscapes (WP1,2 3)",11,1),
("Research",null,"Scaling research (WP1,2,3)",11,1),
("Research",null,"Research on policy processes and science-policy interactions (WP5)",11,1),
("Research",null,"Spatio-temporal assessment, targeting and priority setting (WP3,5)",11,1),
("Research",null,"Design and management of field experiments (WP1)",11,1),
("Research",null,"Rangeland restoration, monitoring and assessment (WP1)",11,1),
("Research",null,"Design and management of water harvesting; modeling (WP1)",11,1),
("Research",null,"Soil health and soil organic carbon assessments (WP1, 2)",11,1),
("Research",null,"Design and management of field experiments, (WP1)",11,1),
("Research",null,"Biodiversity conservation, monitoring and assessment, and adaptation to heat, water stress (WP1)",11,1),
("Research",null,"Design and management of field experiments (WP2)",11,1),
("Research",null,"Livestock, climate modeling and tradeoff analysis (WP2 & 3). CIS development (WP3).",11,1),
("Research",null,"Software systems for CIS, service bundles (WP3), and decision support tools (WP1, WP2, WP5)",11,1),
("Research",null,"Risk scoring systems and service bundles (WP3)",11,1),
("Research",null,"Measuring productivity and GHG outcomes (WP1, 2)",11,1),
("Research",null,"Data collection and analysis (WP1, 2, 5)",11,1),
("Research support",null,"Country point person to track activities and manage partnerships",11,1),
("Research support",null,"Develops and maintains LSCR brand and international visibility",11,1),
("Research support",null,"Coordinates the storage and integration of LCSR data sets",11,1),
("Research support",null,"Design and track project activities, outputs, and outcomes",11,1),
("Research",null,"Provide leadership, assemble teams, develop workplans and ensure implementation, establish internal and external collaborations with partner",5,1),
("Research",null,"Ensuring effective project / workplan implementation for the initiative. Tracking M&E. Annual reporting.",5,1),
("Research",null,"Conduct breeding simulations to guide breeding pipeline design decisions",5,1),
("Research support",null,"Analyze operation costs and budgets for global cost structure database, identify constraints for harmonization, build roadmap to full cost recovery model of shared services, establish TTSS Procurement team",5,1),
("Research",null,"Guide development of costing and forecasting tool",5,1),
("Research",null,"Coordinate services for genotyping and sequencing. Manage logistics for delivering high quality and timely service. Roadmap services for HTP and quality/biochemical testing.",5,1),
("Research",null,"Support development of marker panels at various densities, all crops. Provide genomics and computational expertise to other initiatives",5,1),
("Research",null,"Provide biometrics and modelling support to breeding programs. Areas of particular interest: standardize and automate genetic gain calculations, gBLUP estimates, and target profile environment analyses",5,1),
("Research",null,"Support breeding programs and data management IT teams in describing, harmonizing, and adopting standard operating protocols, workflow charts, and quality controls across the breeding networks, manage documentation, support KPI development, implement transparent change control processes",5,1),
("Research",null,"Innovation readiness and scaling support, facilitate breeding programs in adoption of continuous improvement practices such as LEAN",5,1),
("Research support",null,"Define IT product requirements for breeding DMA and associated tools, lead product roadmap, coordinate inputs from users, stakeholders, and IT technical team, support DMS adoption",5,1),
("Research support",null,"Develop, maintain, and deploy DMS, support business intelligence tool, support GI specific tool development (BPIMS, costing/forecasting tool), support data exchange between DMS",5,1),
("Research",null,"Digitization of data collection workflows, curation of data, timely and responsive in-season user support, expertise on digitization equipment, training on DMS and tools, support end-to-end data management",5,1),
("Research",null,"Stakeholder engagement through strategic and timely communication of change processes, opportunities, objectives, and motivations",5,1),
("Research",null,"Competency assessments, training design, training delivery. Upskill staff in change resilience and effectiveness in a continuous improvement culture",5,1),
("Research",null,"Organize & execute modernization plans, coordinate process improvement networks, coordinate data governance network, facilitate communities of practice, develop BPIMS.",5,1),
("Research",null,"Support staff for access to TTSS and implementation of modernization plans. Stakeholder management & logistics & coordination.",5,1),
("Research",null,"Targeted specialist expertise in areas such as health and safety, mechanization, automation, seed production, facility management, agronomic practices. Technical backstopping, gap analysis of needed skills",5,1),
("Research",null,"Targeted specialist expertise in areas such as high throughput phenotyping, statistical genetics, image analysis, physiology, pathology, biochemistry, crop modelling etc. Technical backstopping, innovation prospecting, gap analysis of needed skills",5,1),
("Research",null,"Prioritization of product market segments (WP1), product profile design (WP2), behavioral research (WP3), pipeline investment cases (WP4), capacity building and scaling (WP5)",6,1),
("Research",null,"Prioritization of market segments (WP1), gender-intentional product profile design (WP2), behavioral research (WP3), capacity building and scaling (WP5)",6,1),
("Research",null,"Prioritization of product market segments (WP1), product profile design (WP2), behavioral research (WP3), capacity building and scaling (WP5)",6,1),
("Research",null,"Prioritization of product market segments (WP1), product profile design (WP2), behavioral research (WP3)",6,1),
("Research",null,"Identification of impact potentials (WP1), ex ante (WP4) and ex post impact assessment (WP5), and MELIA",6,1),
("Research",null,"Prioritization of product market segments (WP1), product profile design (WP2), pipeline investment cases (WP4), capacity building and scaling (WP5)",6,1),
("Research",null,"Prioritization of product market segments (WP1), product profile design (WP2), behavioral research (WP3), capacity building and scaling (WP5)",6,1),
("Research",null,"Global networking and coordination of technical input for product profile design (WP2); dietary assessment and input to WP5 for impact evaluation; technical assistance; capacity building; coordination with WPs 1, 2, 4 and 5.",6,1),
("Research",null,"Assessing feasibility of product profiles (WP2); investment and cost analysis, and alignment of breeding pipelines to product market segments (WP4)",6,1),
("Research",null,"Identification of crop/trait priorities, assessment of pests and diseases and adaptation opportunities to climate change (WP1); expert input in product profiling (WP2)",6,1),
("Research support",null,"Management and curation of data in Global Market Intelligence Platform",6,1),
("Research support",null,"Communication of vision, outputs and outcomes in media",6,1),
("Research",null,"Expertise in specific crops indicated in Work Packages",1,1),
("Research",null,"Product advancement, Variety On farm Testing partners with NARES, Demo for demand generation and Support NARES for early seed generation",1,1),
("Research",null,"Product advancement, Liasion between Seedqual and MIPP for feedback loop",1,1),
("Research",null,"On-farm testing and data collection co-ordination expertise",1,1),
("Research",null,"Co-ordinate/conduct on farm trials, demos either independently or in partnerships with NARES/SMEs",1,1),
("Research",null,"Co-ordinate germplasm dissemination and liaison with NARES and SMEs",1,1),
("Research",null,"Plant health, pest and disease management. Seed degeneration, novel virus diagnostics",1,1),
("Research",null,"Demand led seed systems. Design of seed business models, SME entrepreneur capacity development 

Seeds production economics 

Behavioural economics",1,1),
("Research support",null,"Transdisciplinary research methods 

Research on institutional and partnership arrangements",1,1),
("Research",null,"Conduct gender and social inclusion research for crops and research for development of key knowledge components",1,1),
("Research",null,"Development of knowledge on EGS systems and applicable policies and testing hypothesis and development of relevant recommendation",1,1),
("Research support",null,"Co-ordination of tools for acceleration of variety demand generation, variety adoption and cross lessons implementation",1,1),
("Research support",null,"Conducting data support and ensuring validated data is housed in CG databases",1,1),
("Research",null,"Overall research portfolio management, partnership development",20,1),
("Research",null,"Integration of a gender lens and gender-related research questions into all WPs",20,1),
("Research support",null,"Reporting (including M&E) and finances",20,1),
("Research support",null,"Communication outreach, media/website management",20,1),
("Research support",null,"Design, data analysis and epidemiological modelling, stakeholder engagement, supervision and reporting",20,1),
("Research",null,"Design, implement fieldwork, lab analyses, modelling, student and team supervision",20,1),
("Research",null,"Design, implement fieldwork, lab analyses, epidemiological and sociological analyses, mathematical and economic modelling (shared with WP5), publish, supervision, stakeholder engagement",20,1),
("Research",null,"Design, implement and publish research and supervise researchers and support staff and students.",20,1),
("Research support",null,"Design, execute, and publish studies investigating economic and governance questions. Contribute to impact and process evaluations.",20,1) 
        `;
    const [query, parameters] =
      await queryRunner.connection.driver.escapeQueryWithParameters(
        insertSQL,
        {},
        {}
      );
    const insertedHRTeam = await queryRunner.connection.query(
      query,
      parameters
    );
    console.log(insertedHRTeam);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
